[workspace]
members = ["crates/*"]


    [workspace.package]
    authors     = ["magic-akari <akari.ccino@gmail.com>"]
    description = "A wasm based python formatter"
    edition     = "2021"
    homepage    = "https://github.com/wasm-fmt/ruff_fmt"
    keywords    = ["wasm", "ruff", "python", "formatter"]
    license     = "MIT"
    readme      = "README.md"
    repository  = "https://github.com/wasm-fmt/ruff_fmt"
    version     = "0.0.2"


    [workspace.dependencies]
    ruff_python_formatter = { git = "https://github.com/astral-sh/ruff.git", tag = "v0.0.282" }
    wasm-bindgen          = "0.2.87"

[profile.release]
lto       = true
opt-level = "s"
