[workspace]
members  = ["crates/*"]
resolver = "2"


    [workspace.package]
    authors     = ["magic-akari <akari.ccino@gmail.com>"]
    description = "A wasm based python formatter"
    edition     = "2021"
    homepage    = "https://github.com/wasm-fmt/ruff_fmt"
    keywords    = ["wasm", "ruff", "python", "formatter"]
    license     = "MIT"
    readme      = "README.md"
    repository  = "https://github.com/wasm-fmt/ruff_fmt"
    version     = "0.5.0"


    [workspace.dependencies]
    ruff_fmt_config       = { path = "crates/ruff_fmt_config" }
    ruff_formatter        = { git = "https://github.com/astral-sh/ruff.git", tag = "v0.1.5" }
    ruff_python_formatter = { git = "https://github.com/astral-sh/ruff.git", tag = "v0.1.5" }
    serde                 = { version = "1.0" }
    serde_json            = { version = "1.0" }
    wasm-bindgen          = "0.2.88"


[profile.release]
lto       = true
opt-level = "s"

[patch.crates-io]
unicode_names2 = { path = "crates/unicode_names2_patch" }
