[package]
authors.workspace     = true
description.workspace = true
edition.workspace     = true
homepage.workspace    = true
keywords.workspace    = true
license.workspace     = true
name                  = "ruff_fmt"
publish               = true
repository.workspace  = true
version.workspace     = true

[dependencies]
ruff_python_formatter = { workspace = true }
wasm-bindgen          = { workspace = true }

[dev-dependencies]
testing_macros = "0.2.11"

[lib]
crate-type = ["cdylib", "rlib"]
