name: Publish

on:
    push:
        tags:
            - "v*"

env:
    CARGO_INCREMENTAL: 0
    CARGO_TERM_COLOR: "always"
    RUST_LOG: "off"

jobs:
    wasm-build:
        name: Wasm build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Install wasm-pack
              run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

            - name: Build wasm
              run: ./crates/ruff_fmt/scripts/build.sh

            - name: Package
              run: npm pack
              working-directory: crates/ruff_fmt/pkg

            - name: Upload
              uses: actions/upload-artifact@v4
              with:
                  name: build
                  path: crates/ruff_fmt/pkg

    publish-npm:
        if: startsWith(github.ref, 'refs/tags/v')
        runs-on: ubuntu-latest
        needs: wasm-build
        permissions:
            id-token: write
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version-file: ".node-version"
                  registry-url: "https://registry.npmjs.org"

            - uses: actions/download-artifact@v4
              with:
                  name: build
                  path: crates/ruff_fmt/pkg

            - run: npm publish --provenance
              working-directory: crates/ruff_fmt/pkg
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.FERN_NPM_TOKEN }}
