name: Test

on: [push, pull_request]

env:
    CARGO_INCREMENTAL: 0
    CARGO_TERM_COLOR: "always"
    DIFF: 0
    RUST_LOG: "off"

jobs:
    cargo-fmt:
        name: Cargo fmt
        runs-on: ubuntu-latest
        env:
            RUST_LOG: "0"
        steps:
            - uses: actions/checkout@v3
            - uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  components: rustfmt

            - run: cargo fmt -- --check

    cargo-clippy:
        name: Cargo clippy
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  components: clippy

            - run: cargo clippy

    cargo-check:
        name: Check
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions-rs/toolchain@v1
              with:
                  profile: minimal

            - run: cargo check

    cargo-test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions-rs/toolchain@v1
              with:
                  profile: minimal

            - run: cargo check

            - uses: actions/setup-node@v3
              with:
                  node-version-file: ".node-version"

    wasm-test:
        name: Wasm Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions-rs/toolchain@v1
              with:
                  profile: minimal

            - name: Install wasm-pack
              run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

            - name: Build wasm
              run: ./scripts/build.sh

            - uses: actions/setup-node@v3
              with:
                  node-version-file: ".node-version"

            - name: Node Test
              run: node --test
